// Exact visible source questions, choices and requirements read on 2026-10-01.
export const bilanVersion = 'bilan-formateur-v1' as const
export const bilanTitle = 'WISE-UP — 3. Questionnaire Bilan Formateur' as const
export const bilanQuestions = [
  {
    key: 'email',
    label: 'Adresse e-mail',
    description: '',
    required: true,
    type: 'email',
    choices: [],
    maxLength: 254,
  },
  {
    key: 'school',
    label: 'Établissement',
    description: "Nom de l'établissement où la mission a été réalisée",
    required: true,
    type: 'text',
    choices: [],
    maxLength: 5000,
  },
  {
    key: 'year',
    label: 'Année concernée',
    description: 'Ex. : 2025-2026',
    required: true,
    type: 'text',
    choices: [],
    maxLength: 9,
  },
  {
    key: 'name',
    label: 'Votre nom et prénom (formateur·rice)',
    description: '',
    required: true,
    type: 'text',
    choices: [],
    maxLength: 5000,
  },
  {
    key: 'start',
    label: 'Date de début de mission',
    description: '',
    required: true,
    type: 'date',
    choices: [],
    maxLength: 10,
  },
  {
    key: 'end',
    label: 'Date de fin réelle de mission',
    description: '',
    required: true,
    type: 'date',
    choices: [],
    maxLength: 10,
  },
  {
    key: 'completed',
    label: 'La mission a-t-elle été menée à son terme comme prévu ?',
    description: '',
    required: true,
    type: 'choice',
    choices: ['Oui', 'Partiellement', 'Non'],
    maxLength: 5000,
  },
  {
    key: 'completionReason',
    label: 'Si non ou partiellement, précisez',
    description: '',
    required: false,
    type: 'text',
    choices: [],
    maxLength: 5000,
  },
  {
    key: 'adultCount',
    label: 'Nombre de professionnels effectivement formés',
    description: 'Nombre entier',
    required: true,
    type: 'number',
    choices: [],
    maxLength: 5000,
  },
  {
    key: 'datesRespected',
    label: 'Les dates prévues ont-elles été respectées ?',
    description: '',
    required: true,
    type: 'choice',
    choices: ['Oui', 'Partiellement', 'Non'],
    maxLength: 5000,
  },
  {
    key: 'datesUpdated',
    label: 'Si non, les dates réelles ont-elles bien été communiquées / mises à jour ?',
    description: '',
    required: false,
    type: 'choice',
    choices: ['Oui', 'Non', 'Sans objet'],
    maxLength: 5000,
  },
  {
    key: 'difficulty',
    label: 'Y a-t-il eu une difficulté notable de mise en œuvre à signaler ?',
    description: '',
    required: true,
    type: 'choice',
    choices: ['Non', 'Oui, légère', 'Oui, importante'],
    maxLength: 5000,
  },
  {
    key: 'difficultyDetails',
    label: 'Si oui, merci de préciser brièvement',
    description: '',
    required: false,
    type: 'text',
    choices: [],
    maxLength: 5000,
  },
  {
    key: 'attendanceUrl',
    label: 'Feuilles de présence signées — lien Google Drive',
    description: 'Déposez les feuilles dans votre dossier Drive WISE-UP et collez le lien ici',
    required: true,
    type: 'url',
    choices: [],
    maxLength: 2000,
  },
  {
    key: 'invoiceUrl',
    label: 'Facture — lien Google Drive',
    description: 'Déposez votre facture dans votre dossier Drive WISE-UP et collez le lien ici',
    required: true,
    type: 'url',
    choices: [],
    maxLength: 2000,
  },
  {
    key: 'invoiceAmount',
    label: 'Montant facturé (€)',
    description: 'Montant en euros, sans symbole',
    required: true,
    type: 'text',
    choices: [],
    maxLength: 5000,
  },
  {
    key: 'quote',
    label: 'Avez-vous un verbatim court réutilisable pour la synthèse impact établissement ?',
    description: 'Une phrase ou deux maximum, attribuable à un participant (anonymisé si besoin)',
    required: false,
    type: 'text',
    choices: [],
    maxLength: 5000,
  },
  {
    key: 'hasPhoto',
    label: 'Avez-vous une photo réutilisable de la mission ?',
    description: '',
    required: false,
    type: 'choice',
    choices: ['Oui', 'Non'],
    maxLength: 5000,
  },
  {
    key: 'photoUrl',
    label: 'Si oui, lien vers la ou les photo(s) (Google Drive)',
    description: '',
    required: false,
    type: 'url',
    choices: [],
    maxLength: 2000,
  },
  {
    key: 'hasExample',
    label:
      "Avez-vous un exemple concret de réutilisation / appropriation observé pendant ou à l'issue de la mission ?",
    description: '',
    required: false,
    type: 'choice',
    choices: ['Oui', 'Non'],
    maxLength: 5000,
  },
  {
    key: 'example',
    label: 'Si oui, décrivez cet exemple',
    description: '',
    required: false,
    type: 'text',
    choices: [],
    maxLength: 5000,
  },
  {
    key: 'needsFollowup',
    label: "Y a-t-il un point nécessitant un suivi de l'équipe AMLE ?",
    description: '',
    required: true,
    type: 'choice',
    choices: ['Non', 'Oui'],
    maxLength: 5000,
  },
  {
    key: 'followupDetails',
    label: 'Si oui, merci de préciser',
    description: '',
    required: false,
    type: 'text',
    choices: [],
    maxLength: 5000,
  },
  {
    key: 'recontact',
    label: 'Souhaitez-vous être recontacté·e pour animer une prochaine formation WISE-UP ?',
    description: '',
    required: true,
    type: 'choice',
    choices: [
      'Oui, dans mon établissement',
      'Oui, dans un autre établissement',
      'Oui, dans les deux cas',
      'Non',
      'À rediscuter plus tard',
    ],
    maxLength: 5000,
  },
  {
    key: 'territory',
    label: "Territoire d'intervention souhaité",
    description: 'région, département(s), ville(s), académie(s)',
    required: false,
    type: 'text',
    choices: [],
    maxLength: 5000,
  },
  {
    key: 'radius',
    label:
      'Si vous préférez raisonner en distance, quel rayon maximal de déplacement vous semble envisageable ?',
    description: '',
    required: false,
    type: 'choice',
    choices: ['0 à 20 km', '20 à 50 km', '50 à 100 km', '100 km et plus', 'À préciser autrement'],
    maxLength: 5000,
  },
  {
    key: 'availability',
    label: 'Précision éventuelle sur vos disponibilités ou contraintes de déplacement',
    description: '',
    required: false,
    type: 'text',
    choices: [],
    maxLength: 5000,
  },
  {
    key: 'contractReturned',
    label: 'Avez vous signé et retourné le contrat de formateur wise up ?',
    description: '',
    required: true,
    type: 'checkbox',
    choices: ['OUI', 'Non, merci de le renvoyer'],
    maxLength: 5000,
  },
] as const
