// Exact public wording observed on 2026-10-01; no source/account IDs or answers.
// Preparatory definitions only: production collection is deliberately unavailable.
export type FinalQuestionnaireSlug = 'evaluation-formation' | 'bilan-etablissement'
export type FinalQuestion = {
  key: string
  label: string
  description: string
  section: string
  type: 'email' | 'text' | 'textarea' | 'radio' | 'checkbox' | 'select' | 'scale'
  required: boolean
  choices: string[]
  scaleLabels: string[]
  maxLength: number
  origin: 'source' | 'site'
}
export type FinalQuestionnaireDefinition = {
  slug: FinalQuestionnaireSlug
  kind: string
  version: string
  title: string
  introduction: string
  sourceQuestionCount: number
  sourceRequiredCount: number
  questions: FinalQuestion[]
}
export const finalQuestionnaireDefinitions: FinalQuestionnaireDefinition[] = [
  {
    slug: 'evaluation-formation',
    kind: 'evaluation_fin_formation',
    version: 'evaluation-formation-draft-v1',
    title: 'WISE UP - Évaluation de Fin de Formation',
    introduction:
      'Veuillez prendre quelques minutes pour évaluer votre expérience de formation WISE UP.',
    sourceQuestionCount: 20,
    sourceRequiredCount: 17,
    questions: [
      {
        key: 'email',
        label: 'Adresse e-mail',
        description: '',
        section: 'WISE UP - Évaluation de Fin de Formation',
        type: 'email',
        required: true,
        choices: [],
        scaleLabels: [],
        maxLength: 254,
        origin: 'source',
      },
      {
        key: 'school',
        label: 'Votre établissement',
        description: '',
        section: 'WISE UP - Évaluation de Fin de Formation',
        type: 'text',
        required: true,
        choices: [],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q03',
        label: 'À quel point êtes-vous satisfait(e) globalement de la formation WISE UP ?',
        description: '',
        section: 'WISE UP - Évaluation de Fin de Formation',
        type: 'scale',
        required: true,
        choices: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        scaleLabels: ['Pas du tout satisfait(e)', 'Extrêmement satisfait(e)'],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q04',
        label: 'Dans quelle mesure les objectifs de la formation ont-ils été atteints ?',
        description: '',
        section: 'WISE UP - Évaluation de Fin de Formation',
        type: 'radio',
        required: true,
        choices: [
          'Complètement atteints',
          'Majoritairement atteints',
          'Partiellement atteints',
          'Peu atteints',
          'Pas du tout atteints',
        ],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q05',
        label:
          'Les apports théoriques (santé mentale, bien-être numérique, attention, émotions) étaient :',
        description: '',
        section: 'WISE UP - Évaluation de Fin de Formation',
        type: 'checkbox',
        required: true,
        choices: [
          '1 Peu clairs',
          '2 Assez clairs',
          '3 Clairs',
          '4 Très clairs',
          '5 Excellents et structurants',
        ],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q06',
        label: 'Les pratiques proposées durant la formation vous ont semblé :',
        description: '',
        section: 'WISE UP - Évaluation de Fin de Formation',
        type: 'checkbox',
        required: true,
        choices: [
          '1 Peu utiles',
          '2 Assez utiles',
          '3 Utiles',
          '4 Très utiles',
          '5 Essentielles à ma pratique',
        ],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q07',
        label: 'Supports pédagogiques - Le manuel WISE UP vous paraît :',
        description: '',
        section: 'WISE UP - Évaluation de Fin de Formation',
        type: 'checkbox',
        required: true,
        choices: [
          '1 Peu utile',
          '2 Utile mais dense',
          '3 Clair et aidant',
          'Très clair et structurant',
          'Un véritable support de référence',
        ],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q08',
        label:
          'Expérience vécue et climat de formation: Avez-vous rencontré des difficultés (émotionnelles, pratiques, personnelles) durant la formation ?',
        description: '',
        section: 'WISE UP - Évaluation de Fin de Formation',
        type: 'checkbox',
        required: true,
        choices: ['Non', 'Oui mais gérables', 'Oui, importantes'],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q09',
        label:
          "Si oui : vous êtes-vous senti(e) accueilli(e) et respecté(e) avec ces difficultés  et qu'est-ce qui pourrait être amélioré à ce sujet ?",
        description: '',
        section: 'WISE UP - Évaluation de Fin de Formation',
        type: 'text',
        required: false,
        choices: [],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q10',
        label:
          'Pratiques personnelles (entre les sessions): Avez-vous pratiqué entre les sessions ?',
        description: '',
        section: 'WISE UP - Évaluation de Fin de Formation',
        type: 'checkbox',
        required: true,
        choices: [
          'Oui, pratiques informelles (pauses, respiration, attention au quotidien)',
          'Oui, pratiques formelles (méditations guidées, temps dédiés)',
          'Peu ou pas du tout',
        ],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q11',
        label: 'Qu’est-ce qui a facilité ou freiné votre pratique intersessions ?',
        description: '',
        section: 'WISE UP - Évaluation de Fin de Formation',
        type: 'text',
        required: false,
        choices: [],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q12',
        label:
          "Comment évalueriez-vous la compétence et l'approche pédagogique de l'intervenant(e) ?",
        description: '',
        section: 'WISE UP - Évaluation de Fin de Formation',
        type: 'scale',
        required: true,
        choices: ['1', '2', '3', '4', '5'],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q13',
        label:
          'Apprentissages clés : qu’est-ce que vous retenez comme essentiel de cette formation ?(idée, prise de conscience, outil, posture, pratique…)',
        description: '',
        section:
          "Dans cette section, nous évaluons l'impact sur votre expérience et la transférabilité auprès des élèves",
        type: 'text',
        required: true,
        choices: [],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q14',
        label:
          'Pensez-vous que votre rapport aux écrans et au numérique a évolué grâce à la formation ?',
        description: '',
        section:
          "Dans cette section, nous évaluons l'impact sur votre expérience et la transférabilité auprès des élèves",
        type: 'select',
        required: true,
        choices: ['Pas du tout', 'Un peu', 'Beaucoup', 'De façon significative', 'Je ne sais pas'],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q15',
        label:
          'Pensez-vous que votre posture professionnelle a évolué (présence, régulation émotionnelle, relation aux élèves) ?',
        description: '',
        section:
          "Dans cette section, nous évaluons l'impact sur votre expérience et la transférabilité auprès des élèves",
        type: 'select',
        required: true,
        choices: ['Pas du tout', 'Un peu', 'Beaucoup', 'De façon significative', 'Je ne sais pas'],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q16',
        label: 'Transférabilité auprès des élèves',
        description: '',
        section:
          "Dans cette section, nous évaluons l'impact sur votre expérience et la transférabilité auprès des élèves",
        type: 'select',
        required: true,
        choices: ['Pas du tout', 'Un peu', 'Beaucoup', 'De façon significative', 'Je ne sais pas'],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q17',
        label:
          "Avez-vous l'intention d'appliquer les connaissances et compétences acquises auprès des élèves et dans votre quotidien ?",
        description: '',
        section:
          "Dans cette section, nous évaluons l'impact sur votre expérience et la transférabilité auprès des élèves",
        type: 'radio',
        required: true,
        choices: [
          'Oui, immédiatement',
          'Oui, dans un futur proche',
          'Peut-être, mais sans certitude',
          'Non',
        ],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q18',
        label: 'De quoi auriez-vous besoin pour faciliter cette mise en œuvre ?',
        description: '',
        section:
          "Dans cette section, nous évaluons l'impact sur votre expérience et la transférabilité auprès des élèves",
        type: 'radio',
        required: true,
        choices: [
          'Plus de temps',
          'Plus de confiance / pratique personnelle',
          'Protocole clé en main',
          'Accompagnement / supervision',
          'Appui institutionnel',
          'Autre :',
        ],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q19',
        label:
          'Recommanderiez-vous la formation WISE UP à d’autres professionnels de l’éducation ?',
        description: '',
        section:
          "Dans cette section, nous évaluons l'impact sur votre expérience et la transférabilité auprès des élèves",
        type: 'checkbox',
        required: true,
        choices: ['Non', 'Peut-être', 'Oui sans hésiter'],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q20',
        label: 'Souhaitez-vous ajouter un commentaire, une suggestion ou un témoignage ?',
        description: '',
        section:
          "Dans cette section, nous évaluons l'impact sur votre expérience et la transférabilité auprès des élèves",
        type: 'textarea',
        required: false,
        choices: [],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'year',
        label: 'Année scolaire',
        description: 'Ex. : 2026-2027',
        section: 'Année scolaire',
        type: 'text',
        required: true,
        choices: [],
        scaleLabels: [],
        maxLength: 9,
        origin: 'site',
      },
    ],
  },
  {
    slug: 'bilan-etablissement',
    kind: 'bilan_etablissement',
    version: 'bilan-etablissement-draft-v1',
    title: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
    introduction:
      "Durée estimée : 2 à 3 minutes\n\nCe court questionnaire nous permet de recueillir le point de vue de l'établissement sur le déroulement du programme WISE-UP et ses conditions de poursuite.",
    sourceQuestionCount: 15,
    sourceRequiredCount: 11,
    questions: [
      {
        key: 'email',
        label: 'Adresse e-mail',
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'email',
        required: true,
        choices: [],
        scaleLabels: [],
        maxLength: 254,
        origin: 'source',
      },
      {
        key: 'school',
        label: 'Établissement',
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'text',
        required: true,
        choices: [],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q03',
        label: 'Fonction',
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'radio',
        required: true,
        choices: [
          "Chef d'établissement",
          'Direction adjointe',
          'Référent·e projet',
          'CPE',
          'Enseignant·e référent·e',
          'Autre',
        ],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q04',
        label: "Les étapes prévues du programme ont été réalisées dans l'établissement.",
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'radio',
        required: true,
        choices: ['Oui', 'Partiellement', 'Non'],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q05',
        label: 'Les personnels formés se sont effectivement engagés dans le parcours proposé.',
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'radio',
        required: true,
        choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q06',
        label: "Le programme répond à des besoins éducatifs identifiés dans l'établissement.",
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'radio',
        required: true,
        choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q07',
        label:
          "Le programme peut être intégré de façon réaliste dans le fonctionnement habituel de l'établissement.",
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'radio',
        required: true,
        choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q08',
        label:
          "À l'issue de ce parcours, l'établissement dispose selon vous de personnels en mesure de réutiliser certains apports de WISE-UP.",
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'radio',
        required: true,
        choices: [
          'Pas du tout vrai',
          'Peu vrai',
          'Plutôt vrai',
          'Tout à fait vrai',
          'Je ne sais pas',
        ],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q09',
        label: 'Seriez-vous prêt·e à retravailler avec ce formateur ?',
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'radio',
        required: true,
        choices: ['Pas du tout', 'Plutôt non', 'Plutôt oui', 'Oui sans réserve'],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q10',
        label: 'Si non, pourquoi ?',
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'textarea',
        required: true,
        choices: [],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q11',
        label: 'Principal levier de réussite',
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'radio',
        required: false,
        choices: [
          'Portage de la direction',
          'Engagement des personnels formés',
          'Besoin clairement identifié chez les élèves',
          'Bonne organisation du déploiement',
          "Accompagnement utile par l'organisation / le formateur",
          'Autre',
        ],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q12',
        label: 'Principale difficulté de mise en œuvre',
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'radio',
        required: false,
        choices: [
          'Calendrier / disponibilité des équipes',
          'Mobilisation partielle des personnels',
          'Difficulté à maintenir une continuité après la formation',
          'Difficulté à inscrire le programme dans les pratiques ordinaires',
          'Manque de relais internes',
          'Autre',
        ],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q13',
        label:
          "Pour permettre la poursuite de WISE-UP dans l'établissement, quel serait aujourd'hui le besoin principal ?",
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'radio',
        required: false,
        choices: [
          'Un appui pour organiser la suite après la formation',
          'Des personnels relais clairement identifiés',
          'Des supports simples pour réutiliser les apports',
          'Un temps de suivi après le parcours',
          "Une inscription plus claire dans les temps / instances de l'établissement",
          'Autre',
        ],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q14',
        label: 'Recommanderiez-vous la mise en place de WISE-UP à un autre établissement ?',
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'scale',
        required: true,
        choices: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        scaleLabels: ['Pas du tout', 'Tout à fait'],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'q15',
        label: 'Précision facultative',
        description: '',
        section: 'WISE-UP — 6. Questionnaire Bilan Établissement (référent/direction)',
        type: 'text',
        required: false,
        choices: [],
        scaleLabels: [],
        maxLength: 5000,
        origin: 'source',
      },
      {
        key: 'year',
        label: 'Année scolaire',
        description: 'Ex. : 2026-2027',
        section: 'Année scolaire',
        type: 'text',
        required: true,
        choices: [],
        scaleLabels: [],
        maxLength: 9,
        origin: 'site',
      },
    ],
  },
]
export const finalQuestionnaireDefinition = (slug: string) =>
  finalQuestionnaireDefinitions.find((d) => d.slug === slug)
