// Exact respondent wording, required flags, options and sections observed on 2026-10-01.
// Public question content only: no source IDs, account details or responses.
export type PostformationSlug = 'post-formation' | 'suivi-j45'
export type PostformationQuestion = {
  key: string
  label: string
  description: string
  section: string
  type: 'text' | 'email' | 'textarea' | 'radio' | 'checkbox'
  required: boolean
  choices: string[]
  other: boolean
  maxLength: number
}
export type PostformationDefinition = {
  slug: PostformationSlug
  kind: string
  family: 'postformation_b' | 'suivi_j45'
  dateField: 'date_post_recu' | 'date_suivi_recu'
  version: string
  title: string
  introduction: string
  questions: PostformationQuestion[]
}
export const postformationDefinitions: PostformationDefinition[] = [
  {
    slug: 'post-formation',
    kind: 'post_formation_adultes',
    family: 'postformation_b',
    dateField: 'date_post_recu',
    version: 'post-formation-v1',
    title: 'WISE-UP — B. Questionnaire post formation stagiaires',
    introduction:
      'À remplir à la fin de la formation\nDurée estimée : 3 à 4 minutes\n\nCe questionnaire nous permet de comprendre ce que la formation WISE-UP a rendu plus concret, plus réutilisable et plus facile à mettre en œuvre dans votre contexte professionnel.\nVos réponses serviront à améliorer le programme et à documenter ses effets.',
    questions: [
      {
        key: 'name',
        label: 'Prénom et nom',
        description: '',
        section: 'Informations générales',
        type: 'text',
        required: true,
        choices: [],
        other: false,
        maxLength: 300,
      },
      {
        key: 'email',
        label: 'Email professionnel',
        description: '',
        section: 'Informations générales',
        type: 'email',
        required: true,
        choices: [],
        other: false,
        maxLength: 254,
      },
      {
        key: 'school',
        label: 'Établissement',
        description: '',
        section: 'Informations générales',
        type: 'text',
        required: true,
        choices: [],
        other: false,
        maxLength: 300,
      },
      {
        key: 'year',
        label: 'Année Scolaire concernée : \nEx. : 2026-2027',
        description: '',
        section: 'Informations générales',
        type: 'text',
        required: true,
        choices: [],
        other: false,
        maxLength: 9,
      },
      {
        key: 'q5',
        label: 'Fonction',
        description: '',
        section: 'Informations générales',
        type: 'radio',
        required: true,
        choices: [
          'Enseignant·e',
          'CPE',
          'Personnel de direction',
          'AESH',
          'Personnel éducatif / vie scolaire',
          'Personnel médico-social',
          'Autre',
        ],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q6',
        label:
          "À l'issue de la formation, si une classe est agitée, dispersée ou sursollicitée, je sais quelle action simple proposer immédiatement.",
        description: '',
        section: 'Après la formation',
        type: 'radio',
        required: true,
        choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q7',
        label:
          "À l'issue de la formation, je sais comment aborder avec les élèves les usages numériques dans une logique éducative, sans moraliser.",
        description: '',
        section: 'Après la formation',
        type: 'radio',
        required: true,
        choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q8',
        label:
          "À l'issue de la formation, je vois comment intégrer ces sujets dans le fonctionnement ordinaire de la classe ou de l'établissement.",
        description: '',
        section: 'Après la formation',
        type: 'radio',
        required: true,
        choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q9',
        label:
          "À l'issue de la formation, je suis sensibilisé-e aux enjeux du numérique et leurs effets sur la jeunesse.",
        description: '',
        section: 'Après la formation',
        type: 'radio',
        required: true,
        choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q10',
        label:
          "À l'issue de la formation, je suis consciente de l’impact du numérique dans mon quotidien.",
        description: '',
        section: 'Après la formation',
        type: 'radio',
        required: true,
        choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q11',
        label:
          "À l'issue de la formation, le lien entre les enjeux numériques et la santé mentale est clair pour moi.",
        description: '',
        section: 'Après la formation',
        type: 'radio',
        required: true,
        choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q12',
        label:
          "La formation m'a apporté au moins un format ou une démarche que je peux réutiliser rapidement.",
        description: '',
        section: 'Après la formation',
        type: 'radio',
        required: true,
        choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q13',
        label:
          'Dans les 4 prochaines semaines, je prévois de tester au moins un élément issu de WISE-UP.',
        description: '',
        section: 'Après la formation',
        type: 'radio',
        required: true,
        choices: ['Non', 'Peut-être', 'Oui'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q14',
        label: 'Quel(s) élément(s) comptez-vous tester en premier ?',
        description: '',
        section: 'Mise en application',
        type: 'radio',
        required: false,
        choices: [
          'Temps court de recentrage',
          'Echanges en écoute active ou cercles avec les élèves',
          'Activités autour des usages numériques',
          'Rituel / routine de classe',
          'Sensibilisation théorique (comprendre les enjeux)',
          'Les premiers ateliers',
          'Usage fréquent des mouvements et retour au corps',
          'Autre :',
        ],
        other: true,
        maxLength: 5000,
      },
      {
        key: 'q15',
        label: "Qu'est-ce qui faciliterait le plus le passage de la formation à la pratique ?",
        description: '',
        section: 'Mise en application',
        type: 'radio',
        required: false,
        choices: [
          'Un déroulé simple à réutiliser',
          "Plus d'exemples concrets",
          'Un temps de suivi après la formation',
          "Un appui de l'établissement",
          'Un moment clairement identifié dans le quotidien scolaire',
          'Autre',
        ],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q16',
        label: "Quel est l'apport le plus utile que vous retenez de cette formation ?",
        description: '',
        section: 'Retour rapide sur la formation',
        type: 'text',
        required: false,
        choices: [],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q17',
        label:
          "L'animation de la formation a facilité la compréhension et l'appropriation du programme.",
        description: '',
        section: 'Évaluation de la formation',
        type: 'radio',
        required: true,
        choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q18',
        label: 'Le formateur a proposé un cadre clair, adapté et utile pour le contexte scolaire.',
        description: '',
        section: 'Évaluation de la formation',
        type: 'radio',
        required: true,
        choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q19',
        label: "Le style d'animation du formateur vous a semblé :",
        description: '',
        section: 'Évaluation de la formation',
        type: 'radio',
        required: true,
        choices: ['Peu engageant', 'Correct', 'Engageant', 'Très engageant / fédérant'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q20',
        label:
          'Le formateur a suffisamment montré les pratiques, et pas seulement expliqué la théorie.',
        description: '',
        section: 'Évaluation de la formation',
        type: 'radio',
        required: true,
        choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q21',
        label: "Commentaire facultatif sur l'animation",
        description: '',
        section: 'Évaluation de la formation',
        type: 'text',
        required: false,
        choices: [],
        other: false,
        maxLength: 5000,
      },
    ],
  },
  {
    slug: 'suivi-j45',
    kind: 'suivi_adultes_j45',
    family: 'suivi_j45',
    dateField: 'date_suivi_recu',
    version: 'suivi-j45-v1',
    title: 'WISE-UP — C. Questionnaire suivi adultes formés J+45',
    introduction:
      'Durée estimée : 4 minutes\n\nCe questionnaire de suivi nous permet de mieux comprendre ce que vous avez mis en pratique depuis la formation WISE-UP, les effets observés, et ce qui facilite ou freine l’usage dans votre contexte professionnel.',
    questions: [
      {
        key: 'name',
        label: 'Prénom et nom',
        description: '',
        section: 'Informations générales',
        type: 'text',
        required: true,
        choices: [],
        other: false,
        maxLength: 300,
      },
      {
        key: 'email',
        label: 'Email professionnel',
        description: '',
        section: 'Informations générales',
        type: 'email',
        required: true,
        choices: [],
        other: false,
        maxLength: 254,
      },
      {
        key: 'school',
        label: 'Établissement',
        description: '',
        section: 'Informations générales',
        type: 'text',
        required: true,
        choices: [],
        other: false,
        maxLength: 300,
      },
      {
        key: 'year',
        label: 'Année scolaire',
        description: '',
        section: 'Informations générales',
        type: 'text',
        required: true,
        choices: [],
        other: false,
        maxLength: 9,
      },
      {
        key: 'q5',
        label: 'Session / période de formation concernée',
        description: '',
        section: 'Informations générales',
        type: 'text',
        required: false,
        choices: [],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q6',
        label:
          'Depuis la fin de la formation, avez-vous testé au moins un élément issu de WISE-UP ?',
        description: '',
        section: 'Usage depuis la formation',
        type: 'radio',
        required: true,
        choices: ['Non', 'Oui, 1 fois', 'Oui, 2 à 3 fois', 'Oui, plus de 3 fois'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q7',
        label: 'Quel(s) élément(s) avez-vous testé le plus ?',
        description: '',
        section: 'Usage depuis la formation',
        type: 'radio',
        required: true,
        choices: [
          'Temps court de recentrage',
          'Echanges en écoute active ou cercles avec les élèves',
          'Activité autour des usages numériques',
          'Rituel / routine de classe',
          'Sensibilisation théorique (comprendre les enjeux)',
          'Les premiers ateliers',
          'Usage fréquent des mouvements et retour au corps',
          'Autre :',
        ],
        other: true,
        maxLength: 5000,
      },
      {
        key: 'q8',
        label: "Aujourd'hui, à quelle fréquence utilisez-vous des éléments issus de WISE-UP ?",
        description: '',
        section: 'Usage depuis la formation',
        type: 'radio',
        required: true,
        choices: [
          'Jamais',
          "Moins d'1 fois par semaine",
          'Environ 1 fois par semaine',
          "Plus d'une fois par semaine",
        ],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q9',
        label:
          'Les éléments issus de WISE-UP trouvent une place réaliste dans mon contexte professionnel.',
        description: '',
        section: 'Usage depuis la formation',
        type: 'radio',
        required: true,
        choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q10',
        label: 'Je pourrais partager au moins un élément de WISE-UP à un collègue.',
        description: '',
        section: 'Usage depuis la formation',
        type: 'radio',
        required: true,
        choices: ['Non', 'Peut-être', 'Oui'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q11',
        label: 'Quel a été votre principal frein à la mise en pratique ?',
        description: '',
        section: 'Observations et retours d’usage',
        type: 'radio',
        required: false,
        choices: [
          'Manque de temps',
          'Difficulté à trouver le bon moment',
          'Manque de confiance',
          'Réaction du groupe / de la classe',
          "Manque d'appui dans l'établissement",
          'Autre',
        ],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q12',
        label:
          'Décrivez en quelques mots un usage concret que vous avez testé — ou que vous avez voulu tester.',
        description: "Avec quel groupe ? À quel moment ? Qu'avez-vous proposé ?",
        section: 'Observations et retours d’usage',
        type: 'text',
        required: false,
        choices: [],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q13',
        label: "Quel a été l'effet principal observé ?",
        description: '',
        section: 'Observations et retours d’usage',
        type: 'radio',
        required: false,
        choices: [
          "Plus d'attention",
          "Plus d'apaisement",
          "Meilleure qualité d'échange",
          'Plus de recul sur les usages numériques',
          "Pas d'effet net à ce stade",
          'Autre',
        ],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q14',
        label: 'Souhaitez-vous préciser cet effet observé ?',
        description: '',
        section: 'Observations et retours d’usage',
        type: 'textarea',
        required: false,
        choices: [],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q15',
        label: 'Utilisez-vous actuellement l’application WISE TEACHER ?',
        description: '',
        section: 'Observations et retours d’usage',
        type: 'radio',
        required: true,
        choices: ['Oui', 'Non'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q16',
        label: 'Utilisez-vous l’application Wise Teacher pour votre pratique personnelle ?',
        description: '',
        section: 'Observations et retours d’usage',
        type: 'radio',
        required: true,
        choices: ['Oui, régulièrement', 'Oui, occasionnellement', 'Non'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q17',
        label: 'Utilisez-vous le minuteur de méditation dans l’application ?',
        description: '',
        section: 'Observations et retours d’usage',
        type: 'radio',
        required: true,
        choices: ['Oui', 'Non'],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q18',
        label:
          'Quel type de contenu ou de fonctionnalité utilisez-vous le plus dans l’application ?',
        description: '',
        section: 'Observations et retours d’usage',
        type: 'checkbox',
        required: true,
        choices: [
          'Pratiques guidées / méditations',
          'Ressources pour la classe',
          'Minuteur',
          'Contenus vidéos et autres ressources',
          'Je ne l’utilise pas actuellement',
        ],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q19',
        label:
          'Concernant l’application WISE TEACHER, qu’est-ce qui décrit le mieux votre situation aujourd’hui ?',
        description: '',
        section: 'Observations et retours d’usage',
        type: 'radio',
        required: true,
        choices: [
          'Je l’utilise déjà et je n’ai pas besoin d’appui particulier',
          'Je manque de temps',
          'Je ne sais pas encore comment l’utiliser dans ma pratique',
          'Je ne connais pas bien les contenus disponibles',
          'Je n’en ai pas encore eu l’utilité',
        ],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q20',
        label: 'Dans quel contexte utilisez-vous principalement l’application WISE TEACHER ?',
        description: '',
        section: 'Observations et retours d’usage',
        type: 'radio',
        required: true,
        choices: [
          'En début de cours',
          'Pendant le cours',
          'En fin de cours',
          'À la maison (personnel)',
          'Autre contexte pédagogique',
          'Je ne l’utilise pas',
        ],
        other: false,
        maxLength: 5000,
      },
      {
        key: 'q21',
        label: 'Souhaitez-vous préciser ou apporter des suggestions ?',
        description: '',
        section: 'Observations et retours d’usage',
        type: 'textarea',
        required: false,
        choices: [],
        other: false,
        maxLength: 5000,
      },
    ],
  },
]

export const postformationDefinition = (slug: string) =>
  postformationDefinitions.find((d) => d.slug === slug)
