// Question wording, choices and required flags read from the respondent form.
// No Google identifiers, respondent data or private links belong in this module.
export const preformationVersion = 'preformation-v1'
export const preformationTitle = 'WISE-UP — A. Questionnaire pré formation'
export const preformationIntroduction =
  'À remplir avant le démarrage de la formation\nDurée estimée : 3 minutes\n\nCe questionnaire nous permet de mieux comprendre vos pratiques actuelles et les principaux enjeux rencontrés avant la formation WISE-UP.\nVos réponses serviront de point de départ pour le suivi du programme.'
export const preformationQuestions = [
  {
    key: 'name',
    label: 'Prénom et nom',
    description: '',
    section: 'Informations générales',
    type: 'text',
    required: true,
    choices: [],
    maxLength: 300,
  },
  {
    key: 'email',
    label: 'Email professionnel',
    description: '',
    section: 'Informations générales',
    type: 'email',
    required: true,
    choices: [],
    maxLength: 254,
  },
  {
    key: 'school',
    label: 'Établissement',
    description: '',
    section: 'Informations générales',
    type: 'text',
    required: true,
    choices: [],
    maxLength: 300,
  },
  {
    key: 'year',
    label: 'Année Scolaire concernée',
    description: 'Ex. : 2026-2027',
    section: 'Informations générales',
    type: 'text',
    required: true,
    choices: [],
    maxLength: 9,
  },
  {
    key: 'role',
    label: 'Fonction',
    description: '',
    section: 'Informations générales',
    type: 'choice',
    required: true,
    choices: [
      'Enseignant·e',
      'CPE',
      'Personnel de direction',
      'AESH',
      'Personnel éducatif / vie scolaire',
      'Personnel médico-social',
      'Autre',
    ],
    maxLength: 300,
  },
  {
    key: 'attentionFrequency',
    label:
      "Dans vos activités avec les élèves, à quelle fréquence avez-vous proposé aux élèves un temps court pour se recentrer ou retrouver de l'attention ?",
    description: '',
    section: 'Pratiques actuelles',
    type: 'choice',
    required: true,
    choices: ['Jamais', '1 à 2 fois', '3 à 5 fois', 'Plus de 5 fois'],
    maxLength: 5000,
  },
  {
    key: 'digitalFrequency',
    label:
      "Dans vos activités avec les élèves, à quelle fréquence avez-vous abordé avec les élèves les effets des usages numériques sur l'attention, le stress ou les relations ?",
    description: '',
    section: 'Pratiques actuelles',
    type: 'choice',
    required: true,
    choices: ['Jamais', '1 à 2 fois', '3 à 5 fois', 'Plus de 5 fois'],
    maxLength: 5000,
  },
  {
    key: 'action',
    label:
      "Aujourd'hui, si une classe est agitée, dispersée ou sursollicitée, je sais quelle action simple proposer immédiatement.",
    description: '',
    section: 'Capacité perçue à agir',
    type: 'choice',
    required: true,
    choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
    maxLength: 5000,
  },
  {
    key: 'digitalEducation',
    label:
      "Aujourd'hui, je sais comment aborder avec les élèves les usages numériques dans une logique éducative, sans moraliser.",
    description: '',
    section: 'Capacité perçue à agir',
    type: 'choice',
    required: true,
    choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
    maxLength: 5000,
  },
  {
    key: 'integration',
    label:
      "Aujourd'hui, je vois comment intégrer ces sujets dans le fonctionnement ordinaire de la classe ou de l'établissement.",
    description: '',
    section: 'Capacité perçue à agir',
    type: 'choice',
    required: true,
    choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
    maxLength: 5000,
  },
  {
    key: 'awareness',
    label:
      "Aujourd'hui,  je suis déjà sensibilisé-e aux enjeux du numérique et leurs effets sur la jeunesse.",
    description: '',
    section: 'Capacité perçue à agir',
    type: 'choice',
    required: true,
    choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
    maxLength: 5000,
  },
  {
    key: 'personalImpact',
    label: "Aujourd'hui, je suis consciente de l’impact du numérique dans mon quotidien.",
    description: '',
    section: 'Capacité perçue à agir',
    type: 'choice',
    required: true,
    choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
    maxLength: 5000,
  },
  {
    key: 'mentalHealth',
    label:
      "Aujourd'hui, le lien entre les enjeux numériques et la santé mentale est clair pour moi.",
    description: '',
    section: 'Capacité perçue à agir',
    type: 'choice',
    required: true,
    choices: ['Pas du tout vrai', 'Peu vrai', 'Plutôt vrai', 'Tout à fait vrai'],
    maxLength: 5000,
  },
  {
    key: 'obstacle',
    label: "Quel est aujourd'hui votre principal obstacle ?",
    description: '',
    section: 'Capacité perçue à agir',
    type: 'choice',
    required: true,
    choices: [
      'Manque de temps',
      'Manque de méthode / format',
      'Difficulté à trouver le bon moment',
      'Difficulté à en parler avec les élèves',
      "Manque d'appui dans l'établissement",
      'Autre',
    ],
    maxLength: 5000,
  },
  {
    key: 'problems',
    label: 'Quels sont les 3 problèmes que vous rencontrez fréquemment dans vos classes?',
    description: '',
    section: 'Capacité perçue à agir',
    type: 'textarea',
    required: true,
    choices: [],
    maxLength: 5000,
  },
  {
    key: 'expectations',
    label: "Qu'attendez-vous de cette formation? ",
    description: '',
    section: 'Capacité perçue à agir',
    type: 'text',
    required: true,
    choices: [],
    maxLength: 5000,
  },
  {
    key: 'success',
    label: 'Quels seraient, pour vous, les indicateurs de succès de cette formation? ',
    description: '',
    section: 'Capacité perçue à agir',
    type: 'textarea',
    required: true,
    choices: [],
    maxLength: 5000,
  },
] as const
